### ISSUE TITLE
Tasks without due date have no follow-up tasks

### ISSUE THREAD

**Issue by JensErat** [JensErat/task-relative-recur#2]
Reported in #1 by @Dalker:

> In fact with current TaskWarrior 2.4.0, your plugin does work as intended with relativeRecurDue:... and relativeRecurWait:... combined, but not with relativeRecurWait:... only, in which case the task is not repeated at all (at least on my system).

**Comment by Dalker** [comment]
Works perfectly now with "relativeRecurWait:" only, even in TW 2.4.0. Thanks a lot for the super fast bugfix!
