### ISSUE TITLE
Follow-up tasks are not created

### ISSUE THREAD

**Issue by regagain** [JensErat/task-relative-recur#7]
Hi,

Since I upgraded to Taskwarrior 2.4.2, follow-up tasks are not created, even though I get the `Created follow-up task` message when completing tasks.

It seems the portion of the hook which import the new task is never executed:

```
        # Import the follow-up task
        with tempfile.NamedTemporaryFile() as new_task:
            new_task.write(json.dumps(original));
            new_task.flush();
            add = subprocess.Popen(['task', 'import', new_task.name], env=env)
            add.communicate();
```

Anybody else has the same issue?

Thanks,

**Comment by JensErat** [comment]
I don't have this problem.

What versions of taskwarrior and python are you using? Eg., the output of

```
/usr/bin/env python --version
task version
```

And for taskwarrior, how did you install it (development version, git HEAD, build from somewhere else)?

Could you mark a task as completed with debug flags on, eg.

```
task rc.debug.hooks=2 42 done
```

**Comment by regagain** [comment]
Hi Jens,

```
$ /usr/bin/env python --version
Python 3.4.3
```

```
$ task version
task 2.4.2 built for linux
```

Installed from the Arch feeds: https://www.archlinux.org/packages/community/x86_64/task/

```
$ task rc.debug.hooks=2 137 done
Completed task 8a39fc31-14cc-4b34-95f0-ea7c761f6ef0 'test'.
Completed 1 task.
Timer Config::load (/home/zzz/.taskrc) 0.001976 sec
Found hook script /home/zzz/.task/hooks/on-modify.relative-recur
No context applied.
Derived filter: '( ( ( id == 137 ) ) )'
Filtered 957 tasks --> 1 tasks [all tasks]
Task::modify
Hook: Calling /home/zzz/.task/hooks/on-modify.relative-recur
Hook: input
  {"description":"test","entry":"20150414T152251Z","modified":"20150414T152251Z","relativeRecurDue":"1d","relativeRecurWait":"1d","status":"pending","uuid":"8a39fc31-14cc-4b34-95f0-ea7c761f6ef0"}
  {"description":"test","end":"20150414T152630Z","entry":"20150414T152251Z","modified":"20150414T152251Z","relativeRecurDue":"1d","relativeRecurWait":"1d","status":"completed","uuid":"8a39fc31-14cc-4b34-95f0-ea7c761f6ef0"}
Timer Hooks::execute (/home/zzz/.task/hooks/on-modify.relative-recur) 0.120031 sec
Hook: output
  {"description":"test","end":"20150414T152630Z","entry":"20150414T152251Z","modified":"20150414T152251Z","relativeRecurDue":"1d","relativeRecurWait":"1d","status":"completed","uuid":"8a39fc31-14cc-4b34-95f0-ea7c761f6ef0"}
  Created follow-up task
Hook: Completed with status 0

  pending.data rw O T0137+000~001 L0137+000
completed.data rw - T0820+000~000 L0820+000
     undo.data rw O T0000+000~000 L0004+004
  backlog.data rw O T0000+000~000 L0001+001

Perf task 2.4.2 - 20150414T152630Z init:6160 load:19892 gc:0 filter:3888 commit:4528 sort:0 render:0 hooks:120606 total:155074

Configuration override rc.debug.hooks:2
Created follow-up task
```

**Comment by JensErat** [comment]
Taskwarrior's hook support is really new and still changes rapidly. I guess 2.4.2 from AUR is the official 2.4.2 release, and not from the development branch. Could you try again with the "Versions elsewhere" (hoping they're new enough) or even better compile your own taskwarrior?

The hook requires a development version of taskwarrior of 2.4.2 after 2015-02-22, or a 2.4.3 release (as soon as it's ready).

**Comment by regagain** [comment]
I have tried a few things now, including compiling from source (git/HEAD, git/2.4.2) but I am still facing the same problem.
I have also tried with a new profile, same thing.
I'll try it again this evening, although I'm getting out of ideas.

**Comment by JensErat** [comment]
It seems the error occurs if Python 3 is used. As a temporary workaround, you could enforce Python 2 (is Python 2 available in Arch linux somehow? In Debian I had to enforce Python 3 using `/usr/bin/env python3`).

I will have another look at this though and see what's causing the troubles, so the hook is compatible with Python 3 again.

**Comment by JensErat** [comment]
It was indeed a Python 3 issue. I also enhanced error reporting and fetch the error printed because of stdout being closed instead of simply discarding error messages. Shouldn't have done that from the start anyway.

**Comment by regagain** [comment]
It works like a charm now, thanks!
